### PR TITLE
Export TS interface so it can be use while importing the lib

### PR DESCRIPTION
**Pull request by valentinChantelot**

### CODE REVIEW

**Comment by arunghosh** [comment]
@valentinChantelot Thank you :)

**Comment by valentinChantelot** [comment]
Hi @arunghosh, 👋 

Just to know, did you plan to update the npm package soon ? 😊

**Comment by arunghosh** [comment]
@valentinChantelot Sorry for the delay. I had some issues with linting when trying to take a build. That is why the delay. Will fix and update the package soon.

**Comment by valentinChantelot** [comment]
Oh it's very ok, just wanna know so I can update my work. Thanks !

**Comment by arunghosh** [comment]
@valentinChantelot Published `1.2.0`

**Pull request merged**
